name: CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ui
          npm install

      - name: Build project
        run: |
          cd ui
          npm run build

      - name: Verify build output
        run: |
          if [ ! -d "ui/dist" ] || [ -z "$(ls -A ui/dist)" ]; then
            echo "Build output directory 'ui/dist' is missing or empty"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ui/dist

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: DEV
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ui/dist

      - name: Install gsutil
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install gsutil

      - name: Authenticate with GCP
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Verify bucket name
        run: |
          echo "Bucket name: ${{ vars.UI_BUCKET_NAME }}"

      - name: Deploy to GCP Bucket using rsync
        run: |
          gcloud config set project ${{ vars.GCP_PROJECT_ID }}
          gcloud storage rsync -r ui/dist gs://$${{ vars.UI_BUCKET_NAME }}