name: Deploy to DEV

on:
  workflow_dispatch:

jobs:
  deploy-DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Firebase deploy
        run: gcloud firebase deploy --project stefanstan-play-area-40b27