name: Deploy to DEV

on:
  workflow_dispatch:

jobs:
  deploy-DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: ui/dist

      - name: Verify build output
        run: |
          if [ ! -d "ui/dist" ] || [ -z "$(ls -A ui/dist)" ]; then
            echo "Build output directory 'ui/dist' is missing or empty"
            exit 1
          fi

      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          projectId: ${{ env.FIREBASE_PROJECT_ID }}