name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  workflow_dispatch:


jobs:
  build_and_deploy_dev:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ui
          npm install

      - name: Build project
        run: |
          cd ui
          npm run build
          cd ..

      - name: Verify build output
        run: |
          if [ ! -d "ui/dist" ] || [ -z "$(ls -A ui/dist)" ]; then
            echo "Build output directory 'dist' is missing or empty"
            exit 1
          fi

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Firebase deploy
        run: firebase deploy --project stefanstan-play-area-40b27